openapi: 3.0.1
info:
  description: API for managing contact data
  title: Contacts API
  version: 1.0.0
servers:
- url: /
paths:
  /contacts:
    get:
      responses:
        "200":
          content:
            '*/*':
              schema:
                items:
                  $ref: '#/components/schemas/Contact'
                type: array
          description: OK
      summary: Get all contacts
      x-accepts: '*/*'
    post:
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Contact'
        description: Contact object
        required: true
      responses:
        "201":
          content: {}
          description: Created
        "400":
          content: {}
          description: Bad Request
      summary: Create a new contact
      x-codegen-request-body-name: contact
      x-contentType: '*/*'
      x-accepts: application/json
  /contacts/{id}:
    delete:
      parameters:
      - description: Contact ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "204":
          content: {}
          description: No Content
        "404":
          content: {}
          description: Not Found
      summary: Delete a contact
      x-accepts: application/json
    get:
      parameters:
      - description: Contact ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Contact'
          description: OK
        "404":
          content: {}
          description: Not Found
      summary: Get a contact by ID
      x-accepts: '*/*'
    put:
      parameters:
      - description: Contact ID
        in: path
        name: id
        required: true
        schema:
          type: integer
      requestBody:
        content:
          '*/*':
            schema:
              $ref: '#/components/schemas/Contact'
        description: Contact object
        required: true
      responses:
        "200":
          content: {}
          description: OK
        "400":
          content: {}
          description: Bad Request
        "404":
          content: {}
          description: Not Found
      summary: Update a contact
      x-codegen-request-body-name: contact
      x-contentType: '*/*'
      x-accepts: application/json
components:
  schemas:
    Contact:
      example:
        firstName: firstName
        lastName: lastName
        phone: phone
        id: 0
        email: email
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        phone:
          type: string
        email:
          type: string
      required:
      - firstName
      - phone
      type: object
x-original-swagger-version: "2.0"

