swagger: "2.0"
info:
  version: 1.0.0
  title: Contacts API
  description: API for managing contact data

paths:
  /contacts:
    get:
      summary: Get all contacts
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact"
    post:
      summary: Create a new contact
      parameters:
        - name: contact
          in: body
          description: Contact object
          required: true
          schema:
            $ref: "#/definitions/Contact"
      responses:
        201:
          description: Created
        400:
          description: Bad Request

  /contacts/{id}:
    get:
      summary: Get a contact by ID
      parameters:
        - name: id
          in: path
          description: Contact ID
          required: true
          type: integer
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Contact"
        404:
          description: Not Found

    put:
      summary: Update a contact
      parameters:
        - name: id
          in: path
          description: Contact ID
          required: true
          type: integer
        - name: contact
          in: body
          description: Contact object
          required: true
          schema:
            $ref: "#/definitions/Contact"
      responses:
        200:
          description: OK
        400:
          description: Bad Request
        404:
          description: Not Found

    delete:
      summary: Delete a contact
      parameters:
        - name: id
          in: path
          description: Contact ID
          required: true
          type: integer
      responses:
        204:
          description: No Content
        404:
          description: Not Found

definitions:
  Contact:
    type: object
    properties:
      id:
        type: integer
      firstName:
        type: string
      lastName:
        type: string
      phone:
        type: string
      email:
        type: string
    required:
      - firstName
      - phone
